project_id = "phhyfmztzgkorxhasyaw"

[functions.delete-user-account]
verify_jwt = false

[functions.ai-wellness-insights]
verify_jwt = false

[functions.check-trial]
verify_jwt = false
[functions.check-notifications]
verify_jwt = false
