-- Insert all default breathing exercises as non-custom system exercises (only new ones)
INSERT INTO breathing_exercises (
  title, 
  description, 
  inhale_duration, 
  first_hold_duration, 
  exhale_duration, 
  second_hold_duration, 
  repetitions, 
  is_custom,
  slug,
  detailed_description,
  when_to_use,
  how_it_helps,
  common_mistakes,
  step_by_step_instructions,
  safety_note
) SELECT * FROM (VALUES 
('Pursed Lip Breathing', 'Relaxation and focus', 3, 1, 6, 0, 6, false, 'pursed-lip', 'Slow nasal inhale, then a long, easy exhale through gently pursed lips. Calms the breath, reduces tension, and eases shortness of breath.', ARRAY['Feeling tense, anxious, or short of breath', 'During or after exertion (e.g., stairs, brisk walk)', 'Cool-down after other practices; moments of overwhelm'], 'Lengthens the exhale, that helps the nervous system settle (parasympathetic shift). Creates a gentle back-pressure in the airways and with that it can reduce air trapping and breathlessness. Lowers breathing rate, can improve perceived ease of breathing and focus.', ARRAY['Pressing too hard with the lips (gentle pursing)', 'Shallow inhale; uncontrolled exhale', 'Over-breathing (aim for calm, steady rhythm)'], ARRAY['Sit comfortably, shoulders relaxed.', 'Inhale slowly through your nose for 3.', 'Purse your lips as if whistling or cooling soup.', 'Exhale slowly through pursed lips for 6.', 'Feel the gentle resistance as air flows out.', 'Repeat, maintaining calm and steady rhythm.'], 'Avoid forcing or over-pursing lips. Stop if dizzy or uncomfortable.'),
('Diaphragmatic Breathing', 'Deep relaxation', 4, 1, 6, 0, 6, false, 'diaphragmatic', 'Deep belly breathing that engages the diaphragm for full, relaxing breaths.', ARRAY['Deep relaxation sessions', 'Stress management', 'Before meditation'], 'Activates the parasympathetic nervous system and reduces stress hormones. Improves oxygen efficiency and promotes deep relaxation.', ARRAY['Chest breathing instead of belly', 'Forcing the breath', 'Breathing too fast'], ARRAY['Lie down or sit comfortably.', 'Place one hand on chest, one on belly.', 'Breathe in slowly through nose, expanding belly.', 'Keep chest relatively still.', 'Exhale slowly, letting belly fall.', 'Continue for several minutes.'], 'Start with short sessions. Stop if you feel dizzy or uncomfortable.'),
('Breath Focus Technique', 'Mindful awareness', 4, 2, 6, 0, 10, false, 'breath-focus', 'Mindful breathing with focused attention on the breath to cultivate present-moment awareness.', ARRAY['Meditation practice', 'Anxiety reduction', 'Mindfulness training'], 'Combines breath regulation with mindfulness to reduce anxiety and improve focus. Trains attention and present-moment awareness.', ARRAY['Getting lost in thoughts', 'Judging the breath', 'Trying too hard to control'], ARRAY['Find a comfortable position.', 'Close your eyes or soften your gaze.', 'Focus attention on your natural breath.', 'Notice the sensation of breathing.', 'When mind wanders, gently return to breath.', 'Continue with patient awareness.'], 'Be gentle with yourself. This is a practice, not a performance.'),
('Lion''s Breath', 'Energy and release', 4, 1, 6, 0, 5, false, 'lions-breath', 'Energizing breath with audible exhale that releases tension and builds confidence.', ARRAY['Before presentations', 'To release frustration', 'Energy boost needed'], 'Releases physical and emotional tension through vocal exhale. Can boost confidence and clear mental fog.', ARRAY['Being too self-conscious', 'Not fully engaging the exhale', 'Straining the voice'], ARRAY['Sit tall or kneel comfortably.', 'Inhale deeply through nose.', 'Open mouth wide, stick out tongue.', 'Exhale forcefully with "ahh" sound.', 'Make the exhale strong and audible.', 'Repeat with full engagement.'], 'May feel silly at first - that''s normal! Avoid if you have throat issues.'),
('Alternate Nostril Breathing', 'Balance and focus', 4, 1, 4, 1, 8, false, 'alternate-nostril', 'Traditional technique alternating breath between nostrils to balance the nervous system.', ARRAY['Mental clarity needed', 'Before important decisions', 'Balancing energy'], 'Balances left and right brain hemispheres. Calms the nervous system and improves concentration.', ARRAY['Pressing too hard on nose', 'Rushing the alternation', 'Forcing the breath'], ARRAY['Use right thumb to close right nostril.', 'Inhale through left nostril.', 'Close left nostril with ring finger.', 'Release right nostril, exhale.', 'Inhale right, close with thumb.', 'Release left, exhale left. Repeat.'], 'Keep touch gentle on nose. Stop if you feel dizzy.'),
('Equal Breathing', 'Steady rhythm', 4, 0, 4, 0, 12, false, 'equal-breathing', 'Simple technique with equal inhale and exhale counts for steady, calming rhythm.', ARRAY['Building breath awareness', 'Steady calm needed', 'Before sleep'], 'Creates steady, predictable rhythm that calms the nervous system. Good foundation for other breathing practices.', ARRAY['Making counts too long', 'Breathing too fast', 'Forcing the rhythm'], ARRAY['Find comfortable breathing position.', 'Breathe naturally for a few cycles.', 'Begin counting inhale and exhale.', 'Make both counts equal length.', 'Start with comfortable count (3-5).', 'Maintain steady, easy rhythm.'], 'Choose a count that feels easy and natural. Don''t strain.'),
('Sitali Breath', 'Cooling and calm', 4, 1, 6, 0, 8, false, 'sitali', 'Cooling breath technique that draws air through curled tongue for calming effect.', ARRAY['Feeling overheated', 'Anger or irritation', 'Hot weather'], 'Cools the body and calms pitta (fire) energy. Reduces internal heat and soothes the nervous system.', ARRAY['Forcing tongue curl if not possible', 'Breathing too forcefully', 'Not sealing lips around tongue'], ARRAY['Sit comfortably with spine straight.', 'Curl tongue into tube shape.', 'Inhale slowly through curled tongue.', 'Close mouth, exhale through nose.', 'Feel cooling sensation.', 'Repeat for several cycles.'], 'If you can''t curl tongue, purse lips instead. Avoid in cold weather.'),
('Bee Breath', 'Calming vibration', 4, 2, 6, 0, 6, false, 'bee-breath', 'Humming breath that creates calming vibrations throughout the body.', ARRAY['Deep relaxation needed', 'Stress relief', 'Before meditation'], 'Vibrations stimulate vagus nerve and create immediate calming effect. Sound helps focus the mind.', ARRAY['Humming too loudly', 'Tension in jaw or throat', 'Not breathing fully'], ARRAY['Sit comfortably, close eyes.', 'Place thumbs in ears, fingers over eyes.', 'Inhale normally through nose.', 'Exhale with gentle humming sound.', 'Feel vibrations in head and chest.', 'Continue with steady rhythm.'], 'Keep humming gentle and natural. Stop if you feel dizzy.'),
('Dirga Pranayama', 'Three-part breath', 4, 1, 6, 0, 8, false, 'dirga-pranayama', 'Three-part breathing that fills belly, ribs, and chest sequentially for complete breath.', ARRAY['Deep relaxation', 'Yoga practice', 'Breath awareness training'], 'Maximizes lung capacity and oxygen intake. Promotes deep relaxation and body awareness.', ARRAY['Breathing too quickly', 'Forcing the expansion', 'Not breathing into all three parts'], ARRAY['Lie down or sit tall.', 'Place hands on belly, then ribs.', 'Inhale: belly rises first.', 'Continue: ribs expand out.', 'Finish: gentle chest rise.', 'Exhale in reverse order.'], 'Take your time with each part. This is about awareness, not force.')
) AS new_exercises(title, description, inhale_duration, first_hold_duration, exhale_duration, second_hold_duration, repetitions, is_custom, slug, detailed_description, when_to_use, how_it_helps, common_mistakes, step_by_step_instructions, safety_note)
WHERE new_exercises.title NOT IN (SELECT title FROM breathing_exercises);