
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phhyfmztzgkorxhasyaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoaHlmbXp0emdrb3J4aGFzeWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTQ4NTEsImV4cCI6MjA1OTA3MDg1MX0.BK-H8KPepDb4Nzn5ub19RuzkYKGo156HzI1jfKMsPPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
